source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target "SaleSecretary" do
    pod 'Kingfisher', '~>3.10.1'
    pod 'Alamofire', '~> 4.4.0'
    pod 'SwiftyJSON', '~> 3.1.4'
    pod 'RxSwift', '~> 3.0'
    pod 'RxCocoa', '~> 3.0'
    pod 'SnapKit', '3.0.2'
    pod 'DropDown' 
end
